### ISSUE TITLE
CreateDid misalignment with spec?

### ISSUE THREAD

**Issue by lemoustachiste** [bcgov/trustdidweb-ts#17]
Hey,

I've just noticed something when creating a DID.

Here is my invocation:

```
const did = await createDID({
    domain: 'blockcerts.org',
    signer: createSigner(currentAuthKey[0]!),
    updateKeys: [`did:key:${currentAuthKey[0]!.publicKeyMultibase}`],
    verificationMethods: [
      ...currentAuthKey!,
      // {type: 'assertionMethod', ...availableKeys.secp256k1[0]},
    ]});
```

as in https://github.com/bcgov/trustdidweb-ts/blob/main/test/features.test.ts#L24

This yields a `doc.id` along the lines of `did:tdw:blockcerts.org:5mwc87zmepgqnh6gud7ah0z2uu8d` (see here: https://www.blockcerts.org/.well-known/did.json)

But the spec https://bcgov.github.io/trustdidweb/#method-specific-identifier says that it should be `did:tdw:{SCID}:{domain}` and the subsequent examples in the next paragraph also follow this pattern.

So there seems to be a misalignment somewhere, is it the code implementation or the examples in the spec that are incorrect?

**Comment by swcurran** [comment]
The spec is definitely correct. I’m assuming that the code has not been updated to the latest version of the spec.

@brianorwhatever — can you confirm?

**Comment by brianorwhatever** [comment]
[This commit](https://github.com/bcgov/trustdidweb-ts/commit/749c11ddd1ac137c75b839546b37b81ae54b6226) is where the update was made. Are you sure you are using the latest from the main branch @lemoustachiste?

**Comment by lemoustachiste** [comment]
I'm on an outdated version

Thanks for the prompt response
